[book]
authors = ["TensorStack Authors"]
language = "zh-cn"
multilingual = false
src = "src"
title = "TensorStack AI 计算平台 - User Console 用户手册"

[output.html]
additional-css = ["theme/sidebar.css", "theme/custom.css", "theme/version-dropdown.css"]
additional-js = ["theme/sidebar.js"]
smart-punctuation = true

[output.html.fold]
enable = false

[output.linkcheck]

[preprocessor.tabulate]
command = "./util-tabulate.sh"

[preprocessor.embed]
command = "./util-embed.sh"

[preprocessor.releaselink]
command = "./util-releaselink.sh"

[preprocessor.katex]
after = ["links"]
